name: insta_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.0.0
  dio: ^5.4.1
  shared_preferences: ^2.3.0

  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
